### ISSUE TITLE
Direct station links don't work anymore

### ISSUE THREAD

**Issue by civetworks** [jamespfennell/react-sandbox#27]
It works fine when navigating to a station's timetable from the home page. But when accessing with URL directly, it shows a blank page.

Reproduce:
Open `https://realtimerail.nyc/stops/F02` in the browser directly.

**Comment by jamespfennell** [comment]
Thanks for the bug report!! It also affects the trip page - e.g. https://realtimerail.nyc/routes/G/123150_G..S doesn't work, even if the trip ID is active. The routes pages still work though.

The developer console has lots of errors relating to null values. It seems there are two places where we access a property on a null variable. It's a simple fix.

**Comment by jamespfennell** [comment]
Fixed! https://realtimerail.nyc/stops/F02 now works for me

**Comment by hongfei** [comment]
> Fixed! https://realtimerail.nyc/stops/F02 now works for me

Thanks for the quick fix! The tool is super useful.
