### ISSUE TITLE
Alerts don't render icons in titles

### ISSUE THREAD

**Issue by bporter816** [jamespfennell/react-sandbox#47]
Icons are inserted for alert bodies but not titles. I tried to quickly call the same function on the title but this causes it to be the same size as the big icon at the top of the page, so this probably needs a little bit of custom styling.

<img width="359" alt="Screenshot 2024-02-12 at 12 11 13 PM" src="https://github.com/jamespfennell/realtimerail.nyc/assets/20712582/b963e4aa-6e19-42db-80c7-0784e3d13213">

**Comment by jamespfennell** [comment]
I suspect what’s happening is the CSS styling of the big icon is also used in the title, because of how the CSS inheritance is set up. Probably just another CSS rule is needed to target logos within the alert headings.
