### ISSUE TITLE
Alert date is always epoch

### ISSUE THREAD

**Issue by jbadlato** [jamespfennell/react-sandbox#5]
Looks like [here](https://github.com/jamespfennell/realtimerail.nyc-react/blob/master/src/pages/route/RoutePage.js#L25) you try to get `creation_time` instead of `start_time`?

**Comment by jamespfennell** [comment]
Ha! Awesome catch!

**Comment by jamespfennell** [comment]
![image](https://user-images.githubusercontent.com/12140490/82099683-edcc2180-96d5-11ea-88bf-5402c7215bd6.png)

**Comment by jamespfennell** [comment]
Fixed! Thanks @jbadlato !
