### ISSUE TITLE
Routes missing colors

### ISSUE THREAD

**Issue by bporter816** [jamespfennell/react-sandbox#50]
SIR, Rockaways shuttle, and Franklin Av shuttle are missing the colored stripe along the route. Looks like these are being derived from the values in the routes.txt file from the MTA, but the file doesn't provide colors for these routes. One solution could be adding default/fallback colors in the app.
<img width="354" alt="Screenshot 2024-02-18 at 12 06 14 PM" src="https://github.com/jamespfennell/realtimerail.nyc/assets/20712582/720487e2-27de-4f97-aa68-d5a3a7ea62d6">

**Comment by jamespfennell** [comment]
Hardcoded defaults sound great.

the backend doesn’t have any specialization code for nyc subway GTFS static files, so doing it in the backend be less ideal. So I think it’s best to do this in JavaScript code in the app.
